name: "Build all artifacts"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          path: main
      - name: Enable or disable publishing
        run: |
          if git show -s --format=%B @ | grep -q '\[skip publish\]'; then
            echo "PUBLISH=no" >> "$GITHUB_ENV"
            echo "## Maven publishing" >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "Publishing was **disabled** for this run." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "PUBLISH=yes" >> "$GITHUB_ENV"
          fi
      - uses: actions/checkout@v7
        name: Clone maven
        if: ${{ env.PUBLISH == 'yes' }}
        with:
          token: '${{ secrets.MAVEN_GH_PAT }}'
          path: repo
          fetch-depth: 0
          repository: penguinencounter/mvn
      - name: Link maven
        if: ${{ env.PUBLISH == 'yes' }}
        run: ln -s "$(realpath ./repo/snapshots)" /home/runner/repo
      - name: Create empty maven
        if: ${{ env.PUBLISH == 'no' }}
        run: mkdir -p /home/runner/repo

      - uses: actions/cache@v6
        with:
          path: /home/runner/.gradle
          key: ${{ github.ref }}-gradle-cache-${{ github.run_id }}
          restore-keys: |
            ${{ github.ref }}-gradle-cache
      - name: Java 8
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 8
      - name: Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: build
        run: |
          pushd main || exit 1
          ./gradlew --console=colored -PmavenPath=/home/runner/repo publishAllPublicationsToMountedRepository
          popd
      - name: pull-rebase-push
        if: ${{ env.PUBLISH == 'yes' }}
        run: |
          pushd ./repo || exit 1
          git add .
          if git diff --quiet && git diff --cached --quiet; then
            echo "(Nothing to do...)"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "🚀 Automated snapshot: penguinencounter/FiguraFSB"
          git pull --rebase
          git push -u origin main  # should be fast-forward
          echo "## Maven publishing" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Publishing was completed for this run. The resulting commit is \`$(git show --format=%H -q)\`." >> "$GITHUB_STEP_SUMMARY"
          popd
      - name: collect outputs
        run: |
          mkdir -p /home/runner/artifacts
          mkdir -p /home/runner/sources
          find -H /home/runner/repo -name '*.jar' ! -name '*-sources.jar' -exec cp {} /home/runner/artifacts \;
          find -H /home/runner/repo -name '*-sources.jar' -exec cp {} /home/runner/sources \;
      - uses: actions/upload-artifact@v7
        name: 'Upload builds'
        with:
          name: builds
          path: '/home/runner/artifacts/'
      - uses: actions/upload-artifact@v7
        name: 'Upload sources'
        with:
          name: source-jars
          path: '/home/runner/sources/'
      # I'd like to kill the previous cache here, but it might still be in use by concurrent runs
